<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>libHGPAK</RootNamespace>
    <AssemblyName>libHGPAK</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Build\Debug\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\Build\Release\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release-XML|AnyCPU'">
    <OutputPath>..\Build\Release\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DocumentationFile>..\Build\Release\libHGPAK.xml</DocumentationFile>
    <Optimize>true</Optimize>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="ZstdSharp.Port" Version="0.8.4" />
  </ItemGroup>
  <!--Import Project="..\libHGPAK-Static\libHGPAK-Static.projitems" Label="Shared" /-->
  <PropertyGroup>
    <PostBuildEvent>rem if "$(ConfigurationName)"=="Release" (
rem   "$(ProjectDir)..\BuildTools\_bin\ILMerge.exe" /out:"$(TargetDir)\$(TargetName)-merged$(TargetExt)" "$(TargetPath)" "$(TargetDir)\zlib.net.dll"
rem   del "$(TargetPath)"
rem   move "$(TargetDir)\$(TargetName)-merged$(TargetExt)" "$(TargetPath)"
rem   del "$(TargetDir)$(TargetName).pdb"
rem   move "$(TargetDir)\$(TargetName)-merged.pdb" "$(TargetDir)$(TargetName).pdb"
rem )</PostBuildEvent>
  </PropertyGroup>
  <Import Project="..\libPSARC-Static\libPSARC-Static.projitems" Label="Shared" />
</Project>